### ISSUE TITLE
import failed to translate

### ISSUE THREAD

**Issue by trenGit** [Sensirion/smartgadget-sht4x-housing#2]
Hello, i tried to import these file into Onshape CAD program and they fail to translate do you have a different file type that may be editable in a cad program? thank you

**Comment by quentin-cy** [comment]
Hello @trenGit ,

We made a mistake when uploading the design files and we are currently looking for the correct files that will allow anybody to open/edit.

_Please note that the housing was designed on SolidWorks, therefore the files might not be completely compatible with other software._ 

I will update you as soon as I know more.

Cheers
Q.

**Comment by trenGit** [comment]
very excited to be able to play/ customize with the CAD file. still getting used to various CAD software and i am learning to use the various SHT sensors now. they are very small and i am not used to soldering in this microscopic scale. i whish the smart gadget came with the sht45 chip but i will try to swap the sht40 for the sht45 some other time. thanks!

**Comment by quentin-cy** [comment]
Hello @trenGit 
The [PR #4 ](https://github.com/Sensirion/smartgadget-sht4x-housing/pull/4/)will provide you the design files.
These are SolidWorks files but hopefully you can import them in your CAD software of choice.

Cheers
Q

**Comment by trenGit** [comment]
@qfisch thank you so much !
